"""added caption to images

Revision ID: 2f9817fc7e79
Revises: a484c5760ee6
Create Date: 2018-11-27 16:43:16.953069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f9817fc7e79'
down_revision = 'a484c5760ee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('caption', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'caption')
    # ### end Alembic commands ###
