"""added image to users

Revision ID: 846d9fd3978b
Revises: d9989f05978b
Create Date: 2018-11-26 17:13:22.258398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846d9fd3978b'
down_revision = 'd9989f05978b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_img', sa.Text(),
                                     nullable=False, server_default='/static/download.png'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_img')
    # ### end Alembic commands ###
