"""added followings

Revision ID: 8b2a8de8aeb6
Revises: 98281f54b1ad
Create Date: 2018-11-30 17:47:24.860404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b2a8de8aeb6'
down_revision = '98281f54b1ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_followings_follower_id'), 'followings', ['follower_id'], unique=False)
    op.create_index(op.f('ix_followings_user_id'), 'followings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_followings_user_id'), table_name='followings')
    op.drop_index(op.f('ix_followings_follower_id'), table_name='followings')
    op.drop_table('followings')
    # ### end Alembic commands ###
