"""added is_valid to users

Revision ID: 98281f54b1ad
Revises: 36bf29bec7e8
Create Date: 2018-11-30 15:00:43.352926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98281f54b1ad'
down_revision = '36bf29bec7e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_valid', sa.Boolean(),
                                     server_default='t', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_valid')
    # ### end Alembic commands ###
