"""added is_private to users

Revision ID: d9989f05978b
Revises: f2bd03a56cf9
Create Date: 2018-11-22 16:44:38.307373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9989f05978b'
down_revision = 'f2bd03a56cf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_private', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_private')
    # ### end Alembic commands ###
